# A sample Gemfile
source 'https://rubygems.org'

gem 'rack'
gem 'rack-protection'
gem 'rake'
gem 'unicorn'
gem 'haml-i18n'
gem 'ruby-debug-ide'
gem 'mime-types'
gem 'activesupport'
gem 'json'
gem 'hash-deep-merge'
gem 'rest-client'
gem 'cucumber'
gem 'rspec'
gem 'capybara'
gem 'sass'
gem 'selenium-webdriver'
gem 'uglifier'