/* Generated by Opal 0.6.3 */
(function($opal) {
  var self = $opal.top, $scope = $opal, nil = $opal.nil, $breaker = $opal.breaker, $slice = $opal.slice, $klass = $opal.klass, user = nil;

  $opal.add_stubs(['$attr_accessor', '$==', '$new', '$puts', '$admin?']);
  (function($base, $super) {
    function $User(){};
    var self = $User = $klass($base, $super, 'User', $User);

    var def = self._proto, $scope = self._scope;

    def.name = nil;
    self.$attr_accessor("name");

    def.$initialize = function(name) {
      var self = this;

      return self.name = name;
    };

    return (def['$admin?'] = function() {
      var self = this;

      return self.name['$==']("Admin");
    }, nil) && 'admin?';
  })(self, null);
  user = $scope.User.$new("Bob");
  self.$puts(user);
  return self.$puts(user['$admin?']());
})(Opal);
